SELECT 
    ORD.ORDER_ID, 
    CONCAT(CUS.FIRST_NAME, '', CUS.LAST_NAME) AS 'CUSTOMERS FULL NAME',
	CUS.CITY,
	CUS.STATE,
	ORD.ORDER_DATE,
	SUM (ITM.QUANTITY) AS 'TOTAL UNITS',
	SUM (ITM.QUANTITY * ITM.LIST_PRICE) AS 'REVENUE',
	PRO.PRODUCT_NAME,
	CAT.CATEGORY_NAME,
	STO.STORE_NAME,
	CONCAT(STA.FIRST_NAME, ' ' , STA.LAST_NAME) AS 'STAFF NAME',
	brnd.brand_name as 'Brand Name'
FROM SALES.ORDERS ORD
JOIN SALES.CUSTOMERS CUS ON CUS.CUSTOMER_ID = ORD.CUSTOMER_ID 
JOIN SALES.ORDER_ITEMS ITM ON ITM.ORDER_ID = ORD.ORDER_ID
JOIN PRODUCTION.PRODUCTS PRO ON ITM.PRODUCT_ID= PRO.PRODUCT_ID
JOIN PRODUCTION.CATEGORIES CAT ON CAT.CATEGORY_ID= PRO.CATEGORY_ID
JOIN SALES.STORES STO ON ORD.STORE_ID = STO.STORE_ID
JOIN SALES.STAFFS STA ON STA.STAFF_ID = ORD.STAFF_ID
join production.brands brnd on brnd.brand_id = pro.brand_id
GROUP BY 
    ORD.ORDER_ID, 
    CONCAT(CUS.FIRST_NAME, '', CUS.LAST_NAME),
	CUS.CITY,
	CUS.STATE,
	ORD.ORDER_DATE,
	PRO.PRODUCT_NAME,
	CAT.CATEGORY_NAME,
	STO.STORE_NAME,
	CONCAT(STA.FIRST_NAME, ' ' , STA.LAST_NAME),
	brnd.brand_name